export enum TypeOffre {
    CLOUD = "CLOUD",
    WEB_DEVELOPMENT = "WEB_DEVELOPMENT",
    DATA_SCIENCE = "DATA_SCIENCE",
    CYBER_SECURITY = "CYBER_SECURITY",
    SOFTWARE_ENGINEERING = "SOFTWARE_ENGINEERING",
    MACHINE_LEARNING = "MACHINE_LEARNING",
    MOBILE_APP_DEVELOPMENT = "MOBILE_APP_DEVELOPMENT",
    NETWORK_ENGINEERING = "NETWORK_ENGINEERING",
    DEVOPS = "DEVOPS",
    UX_UI_DESIGN = "UX_UI_DESIGN",
    DATABASE_ADMINISTRATION = "DATABASE_ADMINISTRATION",
    BLOCKCHAIN_DEVELOPMENT = "BLOCKCHAIN_DEVELOPMENT",
    IT_SUPPORT = "IT_SUPPORT",
    GAME_DEVELOPMENT = "GAME_DEVELOPMENT",
    IOT_ENGINEERING = "IOT_ENGINEERING",
    PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT"
  }
  